name: Execute IaC via SSH

on:
  workflow_dispatch:
    inputs:
        username:
            description: 'Username on target machine'
            required: false
            default: 'selubi'
        target:
            description: 'FQDN or IP address of target machine'
            required: true
        commands:
            description: 'Commands to run'
            required: true

jobs:
  ssh-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.TAILSCALE_SSH_KEY }}" > ssh_key
        chmod 600 ssh_key

    - name: Copy injection script
      run: | # Host key check disabled because this workflow is ran on transient container
        scp -i ssh_key -o StrictHostKeyChecking=no \
        ./inject.sh ${{ inputs.username }}@${{ inputs.target }}:/etc/inject.sh

    - name: Run SSH command
      run: | # Host key check disabled because this workflow is ran on transient container
        ssh -i ssh_key -o StrictHostKeyChecking=no \
        ${{ inputs.username }}@${{ inputs.target }} \
        "OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} ${{ inputs.commands }}"
